// client/src/hooks/usePlayers.ts
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import axiosInstance from "../api/axiosInstance";
import { AxiosError } from "axios";

// Common structure for successful API responses
interface ApiResponse<T> {
  message: string;
  data?: T;
  count?: number; // For list responses
}

// Player data structure returned by backend
interface Player {
  _id: string;
  name: string;
  number: number;
  position: string;
  img: string;
  bio: string;
  stats: {
    appearances: number;
    goals?: number;
    assists?: number;
    cleanSheets?: number;
  };
  social?: {
    twitter?: string;
    instagram?: string;
  };
}

// Error response structure from backend
interface BackendErrorResponse {
  message: string;
  stack?: string; // Stack trace usually only in development
}

const usePlayers = () => {
  const queryClient = useQueryClient();

  // Query to fetch all players
  // TData: ApiResponse containing an array of Player
  // TError: AxiosError with BackendErrorResponse data
  // TQueryFnData: The raw data returned by queryFn (also ApiResponse<Player[]>)
  const playersQuery = useQuery<
    ApiResponse<Player[]>,
    AxiosError<BackendErrorResponse>,
    ApiResponse<Player[]>
  >({
    queryKey: ["players"],
    queryFn: async () => {
      const response = await axiosInstance.get("/players");
      return response.data;
    },
    staleTime: 1000 * 60, // Data considered fresh for 1 minute
  });

  // Mutation to create a new player
  // TVariables: Omit<Player, "_id"> as _id is generated by backend
  // TData: ApiResponse containing the created Player
  // TError: AxiosError with BackendErrorResponse data
  const createPlayerMutation = useMutation<
    ApiResponse<Player>,
    AxiosError<BackendErrorResponse>,
    Omit<Player, "_id">
  >({
    mutationFn: async (playerData) => {
      const response = await axiosInstance.post("/players", playerData);
      return response.data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["players"] }); // Invalidate players list to refetch
      console.log("Player created successfully:", data.message);
    },
    onError: (error) => {
      console.error(
        "Failed to create player:",
        error.response?.data?.message || error.message
      );
    },
  });

  const updatePlayerMutation = useMutation<
    ApiResponse<Player>,
    AxiosError<BackendErrorResponse>,
    { id: string; playerData: Partial<Player> }
  >({
    mutationFn: async ({ id, playerData }) => {
      const response = await axiosInstance.put(`/players/${id}`, playerData);
      return response.data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["players"] }); // Invalidate players list
      // Ensure data.data exists before accessing _id
      if (data.data && data.data._id) {
        queryClient.invalidateQueries({ queryKey: ["player", data.data._id] }); // Invalidate specific player if you had a single player query
      }
      console.log("Player updated successfully:", data.message);
    },
    onError: (error) => {
      console.error(
        "Failed to update player:",
        error.response?.data?.message || error.message
      );
    },
  });

  // Mutation to delete a player
  // TVariables: string (id)
  // TData: ApiResponse (no data field needed for delete success)
  // TError: AxiosError with BackendErrorResponse data
  const deletePlayerMutation = useMutation<
    ApiResponse<undefined>,
    AxiosError<BackendErrorResponse>,
    string
  >({
    mutationFn: async (id) => {
      const response = await axiosInstance.delete(`/players/${id}`);
      return response.data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["players"] }); // Invalidate players list
      console.log("Player deleted successfully:", data.message);
    },
    onError: (error) => {
      // error is now AxiosError<BackendErrorResponse>
      console.error(
        "Failed to delete player:",
        error.response?.data?.message || error.message
      );
    },
  });

  return {
    players: playersQuery.data?.data, // Access data.data as per your backend response structure
    playersLoading: playersQuery.isLoading,
    playersError: playersQuery.error,
    createPlayer: createPlayerMutation.mutate,
    updatePlayer: updatePlayerMutation.mutate,
    deletePlayer: deletePlayerMutation.mutate,
    createPlayerMutation,
    updatePlayerMutation,
    deletePlayerMutation,
  };
};

export default usePlayers; // Export the hook as default
