import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import axiosInstance from "../api/axiosInstance";
import { AxiosError } from "axios";
import type {
  ApiResponse,
  BackendErrorResponse,
  ImageUploadResponse,
  Player,
} from "../types";
import { toast } from "react-toastify";

const usePlayers = () => {
  const queryClient = useQueryClient();

  // Query to fetch all players
  // TData: ApiResponse containing an array of Player
  // TError: AxiosError with BackendErrorResponse data
  // TQueryFnData: The raw data returned by queryFn (also ApiResponse<Player[]>)
  const playersQuery = useQuery<
    ApiResponse<Player[]>,
    AxiosError<BackendErrorResponse>,
    ApiResponse<Player[]>
  >({
    queryKey: ["players"],
    queryFn: async () => {
      const response = await axiosInstance.get("/players");
      return response.data;
    },
    staleTime: 1000 * 60, // Data considered fresh for 1 minute
  });

  const uploadImageMutation = useMutation<
    ImageUploadResponse,
    AxiosError<BackendErrorResponse>,
    FormData // Expects FormData for file upload
  >({
    mutationFn: async (formData) => {
      const response = await axiosInstance.post(
        "/players/upload-image",
        formData,
        {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        }
      );
      return response.data;
    },
    onSuccess: (data) => {
      toast.success(data.message || "Image uploaded successfully!");
      console.log("Image uploaded successfully:", data.data);
    },
    onError: (error) => {
      const errorMessage =
        error.response?.data?.message ||
        error.message ||
        "Failed to upload image.";
      toast.error(errorMessage);
      console.error("Failed to upload image:", errorMessage);
    },
  });

  // Mutation to create a new player
  // TVariables: Omit<Player, "_id"> as _id is generated by backend
  // TData: ApiResponse containing the created Player
  // TError: AxiosError with BackendErrorResponse data
  const createPlayerMutation = useMutation<
    ApiResponse<Player>,
    AxiosError<BackendErrorResponse>,
    Omit<Player, "_id">
  >({
    mutationFn: async (playerData) => {
      const response = await axiosInstance.post("/players", playerData);
      return response.data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["players"] });
      toast.success(data.message || "Player created successfully!");
      console.log("Player created successfully:", data.message);
    },
    onError: (error) => {
      const errorMessage =
        error.response?.data?.message ||
        error.message ||
        "Failed to create player.";
      toast.error(errorMessage);
      console.error("Failed to create player:", errorMessage);
    },
  });

  const updatePlayerMutation = useMutation<
    ApiResponse<Player>,
    AxiosError<BackendErrorResponse>,
    { id: string; playerData: Partial<Player> }
  >({
    mutationFn: async ({ id, playerData }) => {
      const response = await axiosInstance.put(`/players/${id}`, playerData);
      return response.data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["players"] }); // Invalidate players list
      // Ensure data.data exists before accessing _id
      if (data.data && data.data._id) {
        queryClient.invalidateQueries({ queryKey: ["player", data.data._id] });
      }
      toast.success(data.message || "Player updated successfully!");
      console.log("Player updated successfully:", data.message);
    },
    onError: (error) => {
      const errorMessage =
        error.response?.data?.message ||
        error.message ||
        "Failed to update player.";
      toast.error(errorMessage);
      console.error("Failed to update player:", errorMessage);
    },
  });

  // Mutation to delete a player
  // TVariables: string (id)
  // TData: ApiResponse (no data field needed for delete success)
  // TError: AxiosError with BackendErrorResponse data
  const deletePlayerMutation = useMutation<
    ApiResponse<undefined>,
    AxiosError<BackendErrorResponse>,
    string
  >({
    mutationFn: async (id) => {
      const response = await axiosInstance.delete(`/players/${id}`);
      return response.data;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["players"] }); // Invalidate players list
      toast.success(data.message || "Player deleted successfully!");
      console.log("Player deleted successfully:", data.message);
    },
    onError: (error) => {
      const errorMessage =
        error.response?.data?.message ||
        error.message ||
        "Failed to delete player.";
      toast.error(errorMessage);
      console.error("Failed to delete player:", errorMessage);
    },
  });

  return {
    players: playersQuery.data?.data, // Access data.data as per your backend response structure
    playersLoading: playersQuery.isLoading,
    playersError: playersQuery.error,
    createPlayer: createPlayerMutation.mutate,
    updatePlayer: updatePlayerMutation.mutate,
    deletePlayer: deletePlayerMutation.mutate,
    uploadImage: uploadImageMutation.mutate,
    createPlayerMutation,
    updatePlayerMutation,
    deletePlayerMutation,
    uploadImageMutation,
  };
};

export default usePlayers; // Export the hook as default
